/**
 * Auth
 */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGOUT = 'LOGOUT'
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'
export const MENU_CHANGE = 'MENU_CHANGE'





/**
 * Profile 
 */
export const GET_PROFILE = "GET_PROFILE"
export const PROFILE_ERROR = "PROFILE_ERROR"
export const CLEAR_PROFILE = "CLEAR_PROFILE"
export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const GET_PROFILES = "GET_PROFILES"

/**
 * Alert 
 */
export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"


/**
 * Story
 */

export const ADD_STORY_CELL = "ADD_STORY_CELL"
export const REMOVE_IMAGE_CONTENT = "REMOVE_IMAGE_CONTENT"
export const REMOVE_STORY_CELL = "REMOVE_STORY_CELL"
export const UPDATE_DROPDOWN_CELL = "UPDATE_DROPDOWN_CELL"
export const INPUT_CHANGE_CELL = "INPUT_CHANGE_CELL"
export const PUBLISH_STORY = "PUBLISH_STORY"

export const ADD_POSTER_IMAGE = "ADD_POSTER_IMAGE"
export const POSTER_IMAGE_LOADING = "POSTER_IMAGE_LOADING"
export const POSTER_IMAGE_FAILED = "POSTER_IMAGE_FAILED"

export const ADD_STORY_IMAGE = "ADD_STORY_IMAGE"
export const STORY_IMAGE_LOADING = "STORY_IMAGE_LOADING"
export const STORY_IMAGE_FAILED = "STORY_IMAGE_FAILED"


export const GET_POPULAR_STORY = "GET_POPULAR_STORY"
export const CLEAR_STORY_CONTENT = "CLEAR_STORY_CONTENT"
export const GET_STORY_BY_ID = "GET_STORY_BY_ID"


/**
 * Members
 */
export const GET_ALL_MEMBERS = "GET_ALL_MEMBERS"